version: '3.7'

services:
  generator:
    image: aspnetcore/generator:multi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT: Development"
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025" # this could be commented if the apps using
                    # it internally in the docker containers
